@TodoApi_HostAddress = http://localhost:5133

Post {{TodoApi_HostAddress}}/todos
Content-Type: application/json

{
  "name":"walk dog",
  "dueDate": "2026-11-19T12:00:00Z",
  "isCompleted": false
}
  
###

@id=0
GET {{TodoApi_HostAddress}}/todos/{{id}}

###

GET {{TodoApi_HostAddress}}/todos/

###

DELETE {{TodoApi_HostAddress}}/todos/{{id}}

###

GET {{TodoApi_HostAddress}}/tasks/{{id}}

###