#if (useDspGenerator)
//  This file is generated by a tool from the file ColorPaletteOverride.zip -- YOU SHOULD NOT EDIT IT manually.
#endif
namespace TubePlayer.Styles;

public sealed partial class ColorPaletteOverride : ResourceDictionary
{
    public ColorPaletteOverride()
    {
        this
            .Build
            (
                r => r
                    .Add<Color>("StatusBarForegroundColor", "#000000", "#FFFFFF")
                    .Add(Theme.Colors.Surface.Default, "#FFFFFF", "#302D37")
                    .Add(Theme.Colors.OnSurface.Default, "#1C1B1F", "#E6E1E5")
                    .Add(Theme.Colors.OnSurface.Variant, "#8A8494", "#C9C5D0")
                    // .Add(Theme.Colors.Surface.Variant, "#F2EFF5", "#47464F")
                    .Add(Theme.Colors.Surface.Variant, "#F85977", "#67E5AD")
                    .Add(Theme.Colors.Error.Default, "#B3261E", "#FFB4AB")
                    .Add(Theme.Colors.Background.Default, "#FCFBFF", "#1C1B1F")
                    .Add(Theme.Colors.Primary.Default, "#5946D2", "#C7BFFF")
                    .Add(Theme.Colors.Primary.Inverse, "#C8BFFF", "#2A009F")
                    .Add(Theme.Colors.OnPrimary.Default, "#FFFFFF", "#2A009F")
                    .Add(Theme.Colors.Primary.Container, "#E5DEFF", "#4129BA")
                    .Add(Theme.Colors.OnPrimary.Container, "#170065", "#E4DFFF")
                    .Add(Theme.Colors.Primary.VariantLight, "#9679FF", "#C8BFFF")
                    .Add(Theme.Colors.Primary.VariantDark, "#0021C1", "#4128BA")
                    .Add(Theme.Colors.Secondary.Default, "#6B4EA2", "#CDC2DC")
                    .Add(Theme.Colors.Secondary.VariantDark, "#3B2574", "#441F8A")
                    .Add(Theme.Colors.Secondary.VariantLight, "#9B7BD5", "#EBE6F1")
                    .Add(Theme.Colors.OnSecondary.Default, "#FFFFFF", "#332D41")
                    .Add(Theme.Colors.Secondary.Container, "#EBDDFF", "#433C52")
                    .Add(Theme.Colors.OnSecondary.Container, "#220555", "#EDDFFF")
                    .Add(Theme.Colors.OnBackground.Default, "#1C1B1F", "#E5E1E6")
                    .Add(Theme.Colors.Surface.Inverse, "#313033", "#E6E1E5")
                    .Add(Theme.Colors.Surface.Tint, "#5946D2", "#C7BFFF")
                    .Add(Theme.Colors.OnSurface.Inverse, "#F4EFF4", "#1C1B1F")
                    .Add(Theme.Colors.Outline.Default, "#79747E", "#928F99")
                    .Add(Theme.Colors.Outline.Variant, "#C9C5D0", "#57545D")
                    .Add(Theme.Colors.OnError.Default, "#FFFFFF", "#690005")
                    .Add(Theme.Colors.Error.Container, "#F9DEDC", "#93000A")
                    .Add(Theme.Colors.OnError.Container, "#410E0B", "#FFDAD6")
                    .Add(Theme.Colors.Tertiary.Default, "#0061A4", "#9FCAFF")
                    .Add(Theme.Colors.OnTertiary.Default, "#FFFFFF", "#003258")
                    .Add(Theme.Colors.Tertiary.Container, "#CFE4FF", "#00497D")
                    .Add(Theme.Colors.OnTertiary.Container, "#001D36", "#D1E4FF")
                    .Add<SolidColorBrush>("StatusBarForegroundBrush", "", "")
                    .Add<Color>("BlueCustomColor", Color.FromArgb(0xFF, 0x15, 0x9B, 0xFF))
                    .Add<Color>("GreenCustomColor", Color.FromArgb(0xFF, 0x67, 0xE5, 0xAD))
                    .Add<Color>("RedCustomColor", Color.FromArgb(0xFF, 0xF8, 0x59, 0x77))
                    .Add<Color>("PurpleCustomColor", Color.FromArgb(0xFF, 0x7A, 0x67, 0xF8))
                    .Add<SolidColorBrush>("BlueCustomBrush", new SolidColorBrush()
                        .Color(ThemeResource.Get<Color>("BlueCustomColor")))
                    .Add<SolidColorBrush>("GreenCustomBrush", new SolidColorBrush()
                        .Color(ThemeResource.Get<Color>("GreenCustomColor")))
                    .Add<SolidColorBrush>("RedCustomBrush", new SolidColorBrush()
                        .Color(ThemeResource.Get<Color>("RedCustomColor")))
                    .Add<SolidColorBrush>("PurpleCustomBrush", new SolidColorBrush()
                        .Color(ThemeResource.Get<Color>("PurpleCustomColor")))
            );
    }
}
